name: vi_test

on:
  push:
    paths-ignore:
      - '**.md'
    
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: test
        run: |
         git clone https://github.com/ryuichiueda/glueutils
         ./glueutils/test/test_all.bash
