name: command_test

on:
  push:
    paths-ignore:
      - '**.md'
    
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: test
        run: |
         git clone -b "${GITHUB_REF#refs/heads/}" https://github.com/ryuichiueda/glueutils
         cd ./glueutils
         make
         ./test/test_all.bash
